# Generated by Django 6.0.6 on 2026-06-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='MILK LAND', max_length=200)),
                ('tagline', models.CharField(default='A Satluj Dairies Venture', max_length=300)),
                ('service_highlight', models.CharField(default='Free Home Delivery', max_length=300)),
                ('address', models.TextField(default='Commercial Market, New City, Bahawalnagar')),
                ('contact_number', models.CharField(default='+923215307273', max_length=50)),
                ('receipt_footer_message', models.TextField(default='Pure Dairy, Fresh Taste, Delivered to Your Doorstep.')),
                ('currency_symbol', models.CharField(default='PKR', max_length=10)),
                ('low_stock_alert_enabled', models.BooleanField(default=True)),
                ('receipt_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
