kind = "web"
previewPath = "/"
title = "MILK LAND POS"
version = "1.0.0"
id = "milkland-pos-django"

[[services]]
localPort = 8000
name = "MILK LAND POS"
paths = ["/"]

[services.development]
run = "cd milkland_pos && python manage.py runserver 0.0.0.0:8000"
